# Form implementation generated from reading ui file 'income.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Income(QtWidgets.QWidget):
    
    
    def setupUi(self, Income):
        Income.setObjectName("Income")
        Income.resize(600, 400)
        Income.setMinimumSize(QtCore.QSize(600, 400))
        Income.setMaximumSize(QtCore.QSize(600, 400))
        self.tableIncome = QtWidgets.QTableWidget(Income)
        self.tableIncome.setGeometry(QtCore.QRect(0, 0, 600, 400))
        self.tableIncome.setMinimumSize(QtCore.QSize(600, 400))
        self.tableIncome.setMaximumSize(QtCore.QSize(600, 400))
        self.tableIncome.setObjectName("tableIncome")
        self.tableIncome.setColumnCount(0)
        self.tableIncome.setRowCount(0)

        self.retranslateUi(Income)
        QtCore.QMetaObject.connectSlotsByName(Income)

    def retranslateUi(self, Income):
        _translate = QtCore.QCoreApplication.translate
        Income.setWindowTitle(_translate("Income", "Form"))
